### ISSUE TITLE
About the paper

### ISSUE THREAD

**Issue by liquor233** [FriedRonaldo/PsyNet#1]
your program is a wonderful work and I am very interested in it.Could you please tell me where can I find your paper? have  it published yet?

**Comment by FriedRonaldo** [comment]
The paper is accepted by AAAI2020 and the conference day starts tomorrow. We did not upload it to arxiv. You might find the paper as a form of pdf later.

**Comment by FriedRonaldo** [comment]
You can download the pdf at https://guidebook.com/g/aaai20/ via downloading the app. and searching AAAI2020.
