### ISSUE TITLE
Hi! I really appreciate your work! I have questions about data loading during training. Both the aircraft dataset and the cub dataset require a train_size.txt, but the data downloaded from the official website does not have these files. How do I load it?

### ISSUE THREAD

**Issue by suyukun666** [FriedRonaldo/PsyNet#2]

**Comment by FriedRonaldo** [comment]
I am sorry for the inconvenience. The files you mentioned seem to be necessary for the evaluation.

For cub, it is "sizes.txt". For Aircraft, the files are "images_{train|test|val}_size.txt".

I upload it to the drive. Thanks for letting me know that.

If you have an issue with this code, please contact me via issue and e-mail. Thx!

**Comment by suyukun666** [comment]
Thx～！
