### ISSUE TITLE
Why are convolution operation used for applying transformations like rotation/translation?

### ISSUE THREAD

**Issue by deepaksuresh** [FriedRonaldo/PsyNet#3]
According to the paper the transformations like translation, reflection are applied on the image. Those transformations seem to be perfromed [here](https://github.com/FriedRonaldo/PsyNet/blob/20f435c9e84a43c9cdad30956ccc2686df1f5261/train.py#L57). From the [code](https://github.com/FriedRonaldo/PsyNet/blob/20f435c9e84a43c9cdad30956ccc2686df1f5261/models/resnet.py#L264), it looks like there are convolutions applied on feature maps and they are labelled as rotation/translation etc.
Also, why is a conv2d used for rotation/shear transform?

**Comment by FriedRonaldo** [comment]
Hi, thanks for your interest.

The conv layers that you mentioned do not conduct the rotation and translation but predict the degree of the transformation applied to the input images. 

They are the same as the linear classifier that predicts the transformation parameter for self supervised learning.
